### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by tyd** [cloudposse/terraform-aws-ses-lambda-forwarder#11]
@osterman @goruha 

Is this project still being maintained? It's been several months since Terraform 0.12.x release and this hasn't been updated yet. Any ETA? Looks like there is an existing PR for it

**Comment by osterman** [comment]
@tyd we only merge 0.12 PRs that have tests. We've upgraded more than 50% of our modules and added tests, but still have some remaining. There are over [150+ terraform modules](https://cpco.io/terraform-modules), so this has been a monumental task (all probono) =)

**Comment by tyd** [comment]
@osterman Thanks for the info. Your efforts are greatly appreciated!

**Comment by osterman** [comment]
@aknysh is updating this module today! =)

**Comment by osterman** [comment]
`0.3.0` released with `HCL2` support https://github.com/cloudposse/terraform-aws-ses-lambda-forwarder/releases/tag/0.3.0
