### ISSUE TITLE
404 error when loading lambda.zip

### ISSUE THREAD

**Issue by tyd** [cloudposse/terraform-aws-ses-lambda-forwarder#13]
When running the example hcl from the readme I'm getting the following error:

> Error: failed to execute "curl": curl: (22) The requested URL returned error: 404 
> on .terraform/modules/ses_lambda_forwarder.artifact/main.tf line 1, in data "external" "curl":
> 1: data "external" "curl" {

It looks like there's a problem with the artifact url here: https://github.com/cloudposse/terraform-aws-ses-lambda-forwarder/blob/f6f93465e77a9bb9b153cfc9cbd431679ff590a2/lambda.tf#L73

**Comment by tyd** [comment]
This happened with both of the following source values:

` source = "git::https://github.com/cloudposse/terraform-aws-ses-lambda-forwarder.git?ref=master"
`
And
`  source = "git::https://github.com/cloudposse/terraform-aws-ses-lambda-forwarder.git?ref=tags/0.3.0"
`

**Comment by 1efty** [comment]
This is also happening for `0.2.0`

## Workaround

Because of #10, fork this project and create new branch based on `0.1.2` and remove `comment` attribute from aws_route53_zone data source in `domain.tf`.

or use

`source = "git::https://github.com/1efty/terraform-aws-ses-lambda-forwarder.git?ref=remove-route53-zone-comment"`

**Comment by osterman** [comment]
Closed in #15

**Comment by mbrunelli** [comment]
I run into this same issue on the latest version: `v0.13`


```
│ Error: External Program Execution Failed
│
│   with module.ses_lambda_forwarder.module.artifact.data.external.curl[0],
│   on .terraform/modules/ses_lambda_forwarder.artifact/main.tf line 3, in data "external" "curl":
│    3:   program    = concat(["curl"], var.curl_arguments, ["--write-out", "{\"success\": \"true\", \"filename_effective\": \"%%{filename_effective}\"}", "-o", local.output_file, local.url])
│
│ The data source received an unexpected error while attempting to
│ execute the program.
│
│ Program: /usr/bin/curl
│ Error Message: curl: (56) The requested URL returned error: 404
│
│ State: exit status 56
```

**Comment by mbrunelli** [comment]
I was able to get this working by building and hosting the Lambda artifact myself. I assume at some point it existed here: https://artifacts.cloudposse.com/terraform-aws-ses-lambda-forwarder/0.13.0/lambda.zip
