### ISSUE TITLE
Dependencies missing from lambda package

### ISSUE THREAD

**Issue by 1efty** [cloudposse/terraform-aws-ses-lambda-forwarder#17]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug

Artifacts do not contain node_modules, thus lambda fails to execute with `ImportError`

## Expected Behavior

Lambda functions properly and contains vendored dependencies.

## Steps to Reproduce

Check the logs, notice that there are no `node_modules` being uploaded

https://github.com/cloudposse/terraform-aws-ses-lambda-forwarder/runs/823734871?check_suite_focus=true

**Comment by Morton** [comment]
Any news on this one?

**Comment by 1efty** [comment]
@Morton since #18 is now merged, update module to reference `?ref=0.6.0`. Tested out myself.
