### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by osterman** [cloudposse/terraform-aws-ses-lambda-forwarder#3]
## what
* Add a `README.yaml`

**Comment by osterman** [comment]
Contact @goruha for a usage example

**Comment by osterman** [comment]
Usage example is here: https://github.com/cloudposse/terraform-root-modules/tree/master/aws/ses

**Comment by vadim-gleyf** [comment]
https://github.com/cloudposse/terraform-aws-ses-lambda-forwarder/pull/5
