### ISSUE TITLE
aws_ses_receipt_rule.default: expected s3_action.0.position to be at least (1), got 0

### ISSUE THREAD

**Issue by claes** [cloudposse/terraform-aws-ses-lambda-forwarder#4]
Hi,
I have use this project for learning aws and terraform. I have created a terraform.tfvars file and when I run terraform apply, I get the message

aws_ses_receipt_rule.default: expected s3_action.0.position to be at least (1), got 0

When I change ses.tf to read position = 1 instead of position = 0, I can apply. Is this a problem in the ses.tf file or is it my usage of it that is wrong?

**Comment by claes** [comment]
Seems like rules are 1-indexed, I needed to change position of the second one to 2. But now it works well. Very nice package!

**Comment by osterman** [comment]
Hej! =)

@claes sorry about that! this module was a bit rushed as we needed it in the last minute for something. The documentation is sparse =)

Here's a reference implementation that might also help: 

https://github.com/cloudposse/terraform-root-modules/tree/master/aws/ses

**Comment by goruha** [comment]
https://github.com/cloudposse/terraform-aws-ses-lambda-forwarder/releases/tag/0.1.2

**Comment by goruha** [comment]
@claes you can use new release ^
